const datatreatments = [{
  _id: "6793711cbbfd50650a64ace4",
  title: "Endometriosis",
  about: "The lining of the uterus builds up in the uterus to create a place for the fertilized egg to implant. Sometimes, however, these mucosal cells also settle outside the uterus and, driven by the hormonal cycle, lead to inflammation, pain and scarring.",
  description: "It is not uncommon for patients to suffer for more than five years before they are diagnosed with endometriosis. Nevertheless, many women live with this problem without knowing about it. It is estimated that around six to ten percent of all women of childbearing age suffer from endometriosis. In Switzerland, this means around 190,000 to 280,000 women. About one in four women who do not become pregnant spontaneously suffers from endometriosis.\n\nThe symptoms may already be present at a young age with the onset of menstruation, or may only increase over the years.\nAfter the onset of the menopause, the symptoms usually decrease significantly or disappear completely.",
  causes: "Why in some women the mucosa from the uterus settles within the pelvis and abdomen is still unclear in detail. Accordingly, the development of endometriosis cannot be prevented. The disease occurs more frequently in some families than in others. If the mother suffered from endometriosis, the daughter has a six times higher risk of also suffering from endometriosis during her reproductive years. Despite this familial clustering, no single endometriosis gene has yet been found.\nEnvironmental influences – in the womb, during the neonatal period – and nutritional factors also appear to play a role.\n\nA possible explanation for the development of endometriosis is so-called “retrograde menstruation”: Instead of the menstrual blood flowing completely through the cervix into the vagina, part of the menstrual blood enters the abdominal cavity through the fallopian tubes together with exfoliated endometrial cells. The inflammation caused by this leads to severe pain by irritating the nerves. This theory can explain the most common sites, which are affected with endometriosis in the abdomen. There are also cases in which the endometrial cells enter the muscle layers of the uterine wall through tiny openings/micro-injuries and can also grow there. In this case we speak of adenomyosis, a close relative of endometriosis.",
  symptoms: "Very often, women tell of severe pain during menses with frequent use of painkillers and sick leave. If this pain has only developed over the years (so-called “secondary dysmenorrhea”), endometriosis is most likely present.\n\nThe following symptoms are still possible:\n\nPain during sexual intercourse\nFeeling of bloating during menstruation\nAbdominal pain regardless of the timing of menstruation\nBack pain\ndisturbed menstrual cycle (intermittent bleeding, prolonged or heavier bleeding)\nnoticeable fatigue and exhaustion\nincreased susceptibility to infections, especially during menstruation\nPain when urinating or blood in the urine\nPain during bowel movements or blood in the stool",
  treatmentdetails: "What endometriosis means for affected women in everyday life can be completely independent of the size and location of the proliferating mucous membrane. Some women do not notice anything, others suffer from the most severe pain.\n\nEndometriosis is treatable but not curable. After surgical removal of the endometriosis, the pain usually subsides, but can reappear as soon as the endometriosis starts to grow again. Hormone therapy is therefore important as a preventive but also pain-relieving measure. The treatment of endometriosis is long and often very stressful for women.\n\nEndometriosis does not generally increase the risk of developing cancer. For certain, rare cancers of the ovary, however, endometriosis appears to be clustered with it.",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1737716011/yyczcseudhhis6c7v9db.jpg",
  img_id: "yyczcseudhhis6c7v9db",
  __v: 0
},
{
  _id: "679876ba39322408ae346cf2",
  title: "Uterine Cancer",
  about: "Uterine cancer, also known as endometrial cancer, affects the lining of the uterus. It is the most common type of cancer in the uterus and typically occurs in postmenopausal women. Early detection is crucial for effective treatment.",
  description: "Treatment for uterine cancer generally involves a combination of surgery, radiation therapy, chemotherapy, and hormone therapy, depending on the stage and type of cancer. The most common treatment is a hysterectomy, which is the removal of the uterus. In some cases, additional treatments like chemotherapy or radiation may be used to ensure that cancer cells are eradicated. Targeted therapy and hormone therapy are emerging treatment options, particularly for less aggressive forms of uterine cancer. A personalized treatment plan is essential based on the stage of cancer and patient health.",
  causes: "The exact cause of uterine cancer is unknown, but several risk factors can increase the likelihood of developing the disease, including:\n\nObesity\nHormonal imbalances, such as high levels of estrogen without enough progesterone\nFamily history of uterine cancer or other related cancers\nPrevious use of tamoxifen (a drug used for breast cancer treatment)",
  symptoms: "Abnormal vaginal bleeding, especially after menopause\nPain or pressure in the pelvic area\nPain during urination or bowel movements\nUnexplained weight loss or fatigue",
  treatmentdetails: "Surgery: A hysterectomy is the most common surgery for uterine cancer, and it may be combined with the removal of ovaries and lymph nodes.\nRadiation Therapy: High-energy beams are directed at the cancer cells to shrink or destroy them. This can be done externally or internally (brachytherapy).\nChemotherapy: Drugs are used to destroy cancer cells or stop their growth. It may be given before or after surgery.\nHormone Therapy: For cancers that are hormone-sensitive, hormone therapy may help stop the growth of cancer cells.\nTargeted Therapy: This involves drugs that specifically target the cancer cells without harming normal cells.",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1738045119/bxitscp08ah2uxcgs2jy.jpg",
  img_id: "bxitscp08ah2uxcgs2jy",
  __v: 0
},
{
  _id: "67987c8b39322408ae346d1b",
  title: "Tubal Recanalization",
  about: "Tubal recanalization is a surgical procedure aimed at opening blocked fallopian tubes to restore fertility in women suffering from tubal factor infertility.",
  description: "Tubal recanalization is typically performed using minimally invasive techniques such as laparoscopy or hysteroscopy. During the procedure, the doctor will attempt to clear the blockage in the fallopian tube(s) using various methods such as a balloon catheter, laser, or surgery. The type of procedure used depends on the location and severity of the blockage.\n\nThis procedure is generally suitable for women whose fallopian tubes are blocked but not excessively damaged, and it offers a chance for women to restore fertility without needing more invasive treatments like IVF.",
  causes: "The causes of tubal factor infertility, which tubal recanalization aims to address, include:\n\nPrevious sterilization or tubal ligation: When a woman has had a tubal ligation, a surgical procedure for permanent contraception, and later desires pregnancy.\nPelvic Inflammatory Disease (PID): An infection caused by bacteria that can scar and block the fallopian tubes.\nEndometriosis: A condition in which tissue similar to the lining inside the uterus grows outside of it, often leading to scar tissue and tubal blockages.\nAbdominal or pelvic surgeries: Surgeries involving the reproductive organs can sometimes lead to adhesions or scarring in the fallopian tubes.\nOther factors such as previous ectopic pregnancies can also contribute to tubal blockages.",
  symptoms: "Women with tubal factor infertility typically do not experience many symptoms outside of infertility. However, some signs that may suggest the presence of tubal blockage include:\n\nDifficulty conceiving despite regular, unprotected intercourse.\nPelvic pain (in some cases, often caused by infections or endometriosis).\nIrregular menstrual cycles (in cases where underlying conditions like endometriosis are involved).\nHistory of PID or sexually transmitted infections (STIs), which increase the risk of tubal blockages.",
  treatmentdetails: "The main objective of tubal recanalization is to restore the normal flow of eggs from the ovaries through the fallopian tubes to the uterus. This allows sperm to fertilize the egg and achieve pregnancy.\n\nLaparoscopy: A camera is inserted through small incisions in the abdomen, allowing the surgeon to view the fallopian tubes and remove or clear any blockages using surgical instruments or lasers. This technique is particularly effective for tubal blockage close to the uterus.\n\nHysteroscopy: A thin, flexible camera is inserted through the cervix and into the uterus, allowing the surgeon to clear the tubes via the cervix. A catheter or balloon can be used to clear the blockage.\n\nBalloon catheterization or laser therapy: In some cases, a balloon catheter is inserted into the tube to open up the blockage. Alternatively, lasers can be used to cut through or vaporize scar tissue causing the blockage.\n\nThe recovery from tubal recanalization is typically quick. Most women can return to normal activities within a few days after the procedure.",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1738046608/u05i2syu0lkgmonwal35.webp",
  img_id: "u05i2syu0lkgmonwal35",
  __v: 0
},
{
  _id: "67987d1339322408ae346d22",
  title: "TOT",
  about: "Tension-free vaginal tape (TOT) is a surgical procedure designed to treat stress urinary incontinence (SUI) in women. Stress urinary incontinence occurs when there is involuntary leakage of urine during physical activities such as coughing, sneezing, or exercise.",
  description: "TOT is a type of mid-urethral sling procedure used to treat stress urinary incontinence. The procedure involves inserting a mesh tape under the urethra through small incisions in the vaginal wall. The tape is tension-free, meaning it doesn’t put pressure on the urethra, which helps avoid irritation or other complications.\n\nThe mesh sling is designed to lift and support the urethra, allowing it to function properly and prevent leakage of urine during physical exertion. The TOT procedure is considered less invasive than other surgical options, with a shorter recovery time.\n\nThe procedure is usually recommended when non-surgical treatments like pelvic floor exercises (Kegel exercises), medications, or lifestyle changes have not been effective in managing symptoms.",
  causes: "Stress urinary incontinence, which TOT treats, can result from several factors, including:\n\nWeak pelvic floor muscles: These muscles support the bladder, urethra, and other pelvic organs. Weakened muscles can lead to SUI, particularly after childbirth.\nChildbirth trauma: Vaginal delivery, particularly when forceps or vacuum is used, can stretch and damage the pelvic floor muscles, contributing to incontinence.\nAging: As women age, the tissues supporting the bladder and urethra weaken, increasing the likelihood of urinary incontinence.\nHormonal changes: Decreased estrogen levels during menopause can affect the pelvic floor muscles and tissues, contributing to incontinence.\nObesity: Excess body weight can put additional pressure on the bladder and pelvic floor, leading to incontinence.\nPrevious pelvic surgery: Surgery involving the pelvic organs may weaken the tissues and muscles, making urinary incontinence more likely.\n",
  symptoms: "The main symptom treated by the TOT procedure is stress urinary incontinence, which is characterized by:\n\nUrinary leakage during physical activities such as coughing, sneezing, laughing, lifting heavy objects, or exercising.\nFrequent urges to urinate, especially when engaging in physical activity.\nInability to control urination during moments of increased abdominal pressure (like during exercise or when bending over).\nIn severe cases, constant leakage of urine, even without any physical exertion.\n",
  treatmentdetails: "The TOT procedure is performed under local or regional anesthesia, and it typically takes about 30 to 60 minutes. The surgeon will insert a small strip of synthetic mesh (the \"tape\") under the urethra through small vaginal incisions. The tape is positioned to support the urethra and prevent urine leakage during physical exertion.\n\nThe procedure is minimally invasive, meaning it requires only small incisions, which reduces the risk of complications and leads to a quicker recovery time compared to other surgeries. The tape is left in place permanently, though it is designed to integrate with the body and will not need removal unless complications arise.\n\nRecovery: Most women experience minimal pain and can return to normal activities within a few weeks. However, they are advised to avoid heavy lifting, high-impact exercise, or other strenuous activities for at least six weeks.\nSuccess Rate: The success rate of TOT is high, with many women experiencing significant improvement or complete resolution of urinary incontinence after the procedure.\nPotential Risks and Complications:\nAlthough TOT is generally considered safe, as with any surgery, there are risks involved:\n\nInfection: As with any surgery, there is a risk of infection, particularly at the incision sites.\nUrinary retention: Some women may experience difficulty in urination or feel unable to completely empty the bladder after the procedure.\nBladder injury: During surgery, there is a small risk of unintentional injury to the bladder.\nMesh complications: In rare cases, the mesh may cause irritation, erosion, or vaginal perforation. This can require removal or adjustment of the tape.\nPersistent incontinence: While TOT has a high success rate, in some cases, urinary incontinence may not be completely resolved, and additional treatments may be necessary.\n",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1738046744/fgeyrhcvno8xru1mndv6.jpg",
  img_id: "fgeyrhcvno8xru1mndv6",
  __v: 0
},
{
  _id: "67987d9d39322408ae346d25",
  title: "MTP",
  about: "Medical Termination of Pregnancy (MTP), commonly referred to as an abortion, is a procedure to terminate a pregnancy. It can be performed using medications or surgical procedures depending on the stage of pregnancy and the patient's health.",
  description: "MTP can be carried out using two main methods:\n\nMedical Abortion (Medication-based):\n\nUsed during the first 9 weeks of pregnancy.\nInvolves taking medications (such as Mifepristone followed by Misoprostol) to expel the fetus.\nThe first pill, Mifepristone, blocks the hormone progesterone, which is needed for pregnancy to continue. After 24–48 hours, the second pill, Misoprostol, is taken to cause the uterus to contract and expel the pregnancy.\nSurgical Abortion:\n\nTypically performed after 9 weeks of pregnancy.\nD&C (Dilatation and Curettage) or Vacuum Aspiration is used to remove the fetus and pregnancy tissue from the uterus.\nMTP is considered a safe procedure when carried out by trained healthcare professionals and is done in accordance with the law and guidelines of each region.",
  causes: "Causes for Medical Termination of Pregnancy:\nRisk to the woman’s health (physical or mental health complications).\nCongenital anomalies in the fetus (such as genetic abnormalities).\nRape or incest (when the pregnancy is the result of violence).\nUnintended pregnancy (for family planning reasons or personal circumstances).\nFailure of contraception (when a woman has contraceptive failure and wishes to terminate the pregnancy).",
  symptoms: "While the decision to terminate a pregnancy can be emotionally challenging, some physical symptoms leading to MTP may include:\n\nUnintended pregnancy confirmed by a positive test.\nFetal abnormality detected via ultrasound or genetic testing.\nHealth risks identified during early prenatal screenings.\nSevere physical or emotional distress caused by the pregnancy.",
  treatmentdetails: "MTP is performed according to the gestational age and health considerations of the woman:\n\nEarly Medical Abortion (up to 9 weeks): Involves a combination of Mifepristone and Misoprostol, which causes the pregnancy to be expelled.\n\nSurgical Abortion: Includes procedures like vacuum aspiration or dilation and curettage, usually done in a clinic or hospital setting.\n\nRecovery: After a medical abortion, cramping and bleeding may occur, and the woman is advised to rest and follow up with a healthcare provider to ensure the procedure was successful.\n\nEmotional Support: Counseling or therapy may be necessary for emotional recovery, as many women experience feelings of grief, guilt, or sadness post-procedure.",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1738046882/fgxnoyxeaxzum9kizumw.webp",
  img_id: "fgxnoyxeaxzum9kizumw",
  __v: 0
},
{
  _id: "679882f639322408ae346d5f",
  title: "Laser Treatment for Piles",
  about: "Laser treatment for piles (hemorrhoids) is a minimally invasive procedure used to treat internal and external hemorrhoids using a laser beam. The technique is commonly referred to as Laser Hemorrhoidoplasty (LHP).",
  description: "Laser treatment for hemorrhoids involves the following steps:\n\nPreparation:\n\nThe procedure is typically done under local anesthesia to numb the area and ensure the patient is comfortable.\nThe patient may be positioned in a specific way for optimal access to the affected area.\nLaser Application:\n\nA laser fiber is inserted into the rectum (for internal hemorrhoids) or near the hemorrhoid (for external hemorrhoids).\nThe laser emits intense light energy, which is precisely targeted to the hemorrhoidal tissue, shrinking and coagulating the blood vessels.\nThe laser energy causes the tissue to become scarred and shrunk, reducing the size of the hemorrhoids.\nProcedure Duration:\n\nThe laser treatment typically takes 15 to 30 minutes, depending on the severity of the hemorrhoids.\nRecovery:\n\nSince laser treatment is minimally invasive, the recovery time is much faster compared to traditional surgical procedures.\nMost patients can return to normal activities within a day or two, although some may experience mild discomfort or swelling.\n",
  causes: "Laser treatment for piles is commonly recommended for the following reasons:\n\nChronic Hemorrhoids: When hemorrhoids do not respond to lifestyle changes or over-the-counter medications.\nSevere Bleeding: When hemorrhoids are causing significant bleeding that cannot be controlled through other methods.\nPain and Discomfort: When hemorrhoids cause constant pain, itching, or discomfort that interferes with daily activities.\nLarge Hemorrhoids: In cases where hemorrhoids are large and have not improved with conservative treatments.",
  symptoms: "Laser treatment is considered for individuals experiencing:\n\nPainful swelling or lumps near the anus.\nBleeding during bowel movements, often seen as bright red blood in the toilet or on toilet paper.\nItching or irritation around the anal region.\nDiscomfort or pain when sitting or walking.\nMucus discharge from the anus.\nA feeling of incomplete evacuation after a bowel movement.",
  treatmentdetails: "Laser treatment for piles typically involves the following steps:\n\nConsultation and Evaluation:\n\nThe doctor will evaluate the severity of hemorrhoids through a physical exam and may perform a rectal examination to assess the condition.\nImaging or proctoscopy may be used to evaluate internal hemorrhoids.\nLaser Procedure:\n\nThe procedure is done under local anesthesia, and the laser fiber is inserted through the rectum to target internal hemorrhoids or directly near external hemorrhoids.\nThe laser energy is used to coagulate and shrink the hemorrhoidal tissue, which helps stop the bleeding and relieve pain.\nPost-Treatment Care:\n\nRecovery time is typically quick, with most patients experiencing minimal pain and no scarring.\nPatients are advised to avoid strenuous activities for a few days to allow the area to heal.\nA high-fiber diet and drinking plenty of fluids are recommended to prevent constipation and further strain during bowel movements.",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1738048252/uvpspzkiriavfeatygrx.jpg",
  img_id: "uvpspzkiriavfeatygrx",
  __v: 0
},
{
  _id: "6798835239322408ae346d66",
  title: "vNOTES Hysterectomy",
  about: "vNOTES Hysterectomy (vaginal Natural Orifice Transluminal Endoscopic Surgery) is an advanced, minimally invasive surgical procedure used to remove the uterus through the vaginal canal using specialized endoscopic techniques.",
  description: "In vNOTES Hysterectomy, the uterus is removed using instruments inserted through the vaginal canal, along with a flexible endoscope. The process involves the following steps:\n\nPre-Surgical Preparation:\nThe patient is placed under general anesthesia.\nDetailed imaging (e.g., ultrasound, MRI) is often performed to assess the uterus' size and position, along with a pelvic exam to determine the best surgical approach.\nProcedure:\nAccess through the vagina: The surgeon uses specialized endoscopic tools and a flexible camera (endoscope) to view and operate on the uterus.\nThe uterus is detached from its ligaments, ovaries, and surrounding tissues.\nThe uterus is then carefully removed through the vaginal canal.\nNo external incisions are made, making the procedure less invasive and reducing recovery time.\nAdvantages over Traditional Vaginal Hysterectomy:\nEnhanced visualization: The endoscopic tools provide clear views of the surgical site.\nMinimal scarring: Since the procedure is done through the vagina, there are no external incisions, leading to no visible scarring.\nReduced recovery time: Patients tend to recover faster than with traditional abdominal or vaginal hysterectomy.\nLower risk of complications: The procedure is minimally invasive, which may lead to a decreased risk of infection and bleeding.\n",
  causes: "Some common causes or conditions leading to the need for vNOTES hysterectomy include:\n\nUterine fibroids, which may cause heavy menstrual bleeding, pelvic pain, and infertility.\nEndometriosis, which leads to pain, heavy menstrual bleeding, and infertility.\nPelvic organ prolapse, in which the uterus or other pelvic organs drop into the vaginal canal.\nCancerous conditions (such as uterine or cervical cancer), when a hysterectomy is necessary for treatment.\nChronic abnormal bleeding, especially when medical treatments like hormonal therapy or medications have failed.",
  symptoms: "Severe pelvic pain, particularly in the case of endometriosis or fibroids.\nHeavy or irregular menstrual bleeding that disrupts daily life.\nPain during sexual intercourse, often due to uterine conditions or prolapse.\nChronic back pain or pelvic pressure, typically caused by large fibroids or uterine prolapse.\nAbnormal discharge or symptoms related to uterine cancer or other gynecological conditions.",
  treatmentdetails: "The vNOTES Hysterectomy involves the following key steps:\n\nConsultation & ]Evaluation:\n\nA thorough pelvic exam and imaging tests are conducted to evaluate the size and health of the uterus, as well as any other factors affecting the procedure.\nPreoperative counseling is provided to ensure the patient understands the process and risks.\nSurgical Procedure:\n\nThe surgery is done through the vaginal canal, and the surgeon uses specialized tools to detach the uterus from its connections to the pelvic floor.\nThe uterus is carefully removed through the vaginal route, and any necessary repairs or procedures are performed.\nThe entire process is guided by endoscopic visualization, ensuring the surgeon has a clear view of the surgical area.\nPost-Surgical Care:\n\nRecovery times are generally shorter than with traditional abdominal or vaginal hysterectomy.\nPatients are monitored for potential complications such as bleeding or infection.\nA follow-up appointment is usually scheduled to assess healing and ensure there are no issues post-surgery.\n",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1738048343/avoypawfhm2lfu5ui5fp.jpg",
  img_id: "avoypawfhm2lfu5ui5fp",
  __v: 0
},
{
  _id: "6798837d39322408ae346d6d",
  title: "NDVH",
  about: "A Natural Descent Vaginal Hysterectomy (NDVH) is a minimally invasive surgical procedure for the removal of the uterus (hysterectomy) that is performed through the vaginal canal, without the need for abdominal incisions.",
  description: "NDVH is typically performed for the treatment of various gynecological conditions. The procedure involves:\n\nPre-Surgical Preparation:\n\nThe patient is given general anesthesia or regional anesthesia to ensure comfort during the procedure.\nA vaginal examination is performed to evaluate the uterus size, position, and any potential complications.\nProcedure:\n\nThe surgeon accesses the uterus through the vaginal canal.\nThe cervix and uterus are detached from surrounding tissues, and the uterus is carefully removed through the vaginal opening.\nThe procedure is performed without the need for large abdominal incisions, and minimal manipulation is used to gently guide the uterus out.\nAdvantages over Abdominal Hysterectomy:\n\nSmaller incisions (no abdominal cuts).\nLower risk of infection due to reduced exposure.\nFaster recovery time and less postoperative pain.\nLess scarring since the incision is internal and vaginal.\nRecovery:\n\nRecovery is typically faster compared to traditional abdominal hysterectomy, with most women returning to normal activities within 6–8 weeks.\nWomen may experience some vaginal bleeding, mild cramping, and discomfort initially.\nThe need for postoperative care may include avoiding heavy lifting, sexual activity, and strenuous exercise for several weeks.",
  causes: "The primary cause for recommending an NDVH procedure includes:\n\nUterine disorders that do not respond to medical treatments (such as large fibroids or abnormal uterine bleeding).\nPelvic organ prolapse that significantly affects the quality of life.\nFailed conservative treatments for conditions like endometriosis or chronic pelvic pain.\nDesire to avoid abdominal surgery due to faster recovery and fewer complications.",
  symptoms: "Some symptoms that might lead to the need for an NDVH include:\n\nHeavy or prolonged menstrual bleeding.\nPain during intercourse.\nChronic pelvic or abdominal pain.\nUterine prolapse, causing pelvic pressure, urinary incontinence, or difficulty with bowel movements.\nAbnormal findings in routine gynecological exams that require surgical intervention.\nSevere pelvic pain, particularly in the case of endometriosis or fibroids.\nHeavy or irregular menstrual bleeding that disrupts daily life.\nPain during sexual intercourse, often due to uterine conditions or prolapse.\nChronic back pain or pelvic pressure, typically caused by large fibroids or uterine prolapse.\nAbnormal discharge or symptoms related to uterine cancer or other gynecological conditions.",
  treatmentdetails: "The process of performing NDVH is as follows:\n\nSurgical Procedure:\n\nThe uterus is detached from surrounding tissues (ligaments, fallopian tubes, ovaries) and removed through the vaginal canal.\nThe cervix may be removed if necessary, depending on the specific condition being treated.\nThe vaginal cavity is then closed using sutures, and the internal tissue is repaired.\nPostoperative Care:\n\nWomen are monitored in the hospital for a short period after surgery.\nTypically, the patient will be advised to avoid sexual activity, heavy lifting, and strenuous exercise for several weeks.\nFollow-up visits with the doctor are necessary to ensure healing and assess any complications.\n",
  img: "https://res.cloudinary.com/dqmjfxntr/image/upload/v1738048386/waexlazadi69tdosoyyk.jpg",
  img_id: "waexlazadi69tdosoyyk",
  __v: 0
}]

export { datatreatments };